services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - pg-social-volume:/var/lib/postgresql/data
    networks:
      - social-postify-network
  social-postify:
    build: .
    container_name: social-postify
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - social-postify-network
    depends_on:
      - postgres
networks:
  social-postify-network:
volumes:
  pg-social-volume:
